### ISSUE TITLE
RefreshToken

### ISSUE THREAD

**Issue by Sejushi** [KoenZomers/OneDriveAPI#17] opened 2019-02-14 13:58 UTC
Hi,
I'm using OneDriveGraphApi to uploading files. with function OneDriveApi.AuthenticateUsingRefreshToken.

Everything works very well but my refresh token is changing after few weeks and I have to put into my code new token... what I should do to avoid this problem?

**Comment by KoenZomers** [comment] 2019-02-22 15:43
On the OneDriveApi instance on which you call AuthenticateUsingRefreshToken you will find a property called AccessToken which is of type OneDriveAccessToken. This on its turn has a property RefreshToken. After doing your authentication, simply get the value of this RefreshToken and update your local config to use that the next time. It should work for up to about 3 months I believe it is at present. Then it will stop working. This is by design. Not sure if there’s an option already by now to overrule that. Haven’t checked recently.

**Comment by KoenZomers** [comment] 2019-05-06 14:21
Closing this item as there have not been any updates.

**Closed as completed by KoenZomers** 2019-05-06 14:21 UTC
Labels: question
